version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: facade/ignition
    versions:
    - 1.16.16
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
